import {
  Box,
  Globe,
  LayoutDashboardIcon,
  PackageOpen,
  Settings,
  Users,
} from "lucide-react";

import Tool1 from "@/assets/img/tool-1.svg";
import Tool2 from "@/assets/img/tool-2.svg";

export const items = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboardIcon,
  },
  {
    title: "Supplier",
    url: "/supplier",
    icon: Users,
  },
  {
    title: "Product",
    url: "/products",
    icon: Box,
  },
  {
    title: "Product Export",
    url: "/product-export",
    icon: PackageOpen,
  },
  {
    title: "Company Info",
    url: "/company-info",
    icon: Globe,
  },
  {
    title: "Settings",
    url: "/setting",
    icon: Settings,
  },
];

export const category = [
  {
    id: 1,
    name: "Hand Tools",
    subcategories: [
      "Hammers",
      "Screwdrivers",
      "Wrenches",
      "Pliers",
      "Chisels",
      "Measuring Tapes",
      "Utility Knives",
    ],
  },
  {
    id: 2,
    name: "Power Tools",
    subcategories: [
      "Drills",
      "Saws (Circular, Jigsaw, Reciprocating)",
      "Grinders",
      "Sanders",
      "Nail Guns",
      "Rotary Tools",
      "Heat Guns",
    ],
  },
  {
    id: 3,
    name: "Tool Storage & Organization",
    subcategories: [
      "Toolboxes",
      "Tool Bags",
      "Workbenches",
      "Tool Chests",
      "Pegboards",
      "Drawer Organizers",
    ],
  },
  {
    id: 4,
    name: "Electrical Tools",
    subcategories: [
      "Multimeters",
      "Voltage Testers",
      "Wire Strippers",
      "Crimping Tools",
      "Soldering Irons",
      "Circuit Finders",
    ],
  },
  {
    id: 5,
    name: "Construction & Heavy Tools",
    subcategories: [
      "Concrete Mixers",
      "Jackhammers",
      "Scaffolding",
      "Ladders",
      "Wheelbarrows",
      "Compactors",
    ],
  },
  {
    id: 6,
    name: "Automotive Tools",
    subcategories: [
      "Socket Sets",
      "Torque Wrenches",
      "Engine Hoists",
      "Brake Tools",
      "Diagnostic Scanners",
      "Battery Chargers",
    ],
  },
  {
    id: 7,
    name: "Measuring & Layout Tools",
    subcategories: [
      "Levels",
      "Laser Measuring Tools",
      "Calipers",
      "Micrometers",
      "Squares",
      "Angle Finders",
    ],
  },
  {
    id: 8,
    name: "Gardening & Outdoor Tools",
    subcategories: [
      "Shovels",
      "Rakes",
      "Pruners",
      "Lawn Mowers",
      "Leaf Blowers",
      "Hedge Trimmers",
    ],
  },
];

export const options = [
  { label: "Professional", emoji: "💼" },
  { label: "Friendly", emoji: "🤗" },
  { label: "Creative", emoji: "💡" },
  { label: "Technical", emoji: "🛠️" },
];

export const contactData = [
  {
    name: "DigiMark Developers",
    website: "digimarkdevelopers@gmail.com",
    address: "101 E Wacker Dr Chicago IL",
    postal_code: "60601",
  },
  {
    name: "Tech Solutions",
    website: "techsolutions@example.com",
    address: "202 N Michigan Ave Chicago IL",
    postal_code: "60602",
  },
  {
    name: "Tech Solutions",
    website: "techsolutions@example.com",
    address: "202 N Michigan Ave Chicago IL",
    postal_code: "60602",
  },

  {
    name: "Tech Solutions",
    website: "techsolutions@example.com",
    address: "202 N Michigan Ave Chicago IL",
    postal_code: "60602",
  },

  {
    name: "Tech Solutions",
    website: "techsolutions@example.com",
    address: "202 N Michigan Ave Chicago IL",
    postal_code: "60602",
  },

  {
    name: "Tech Solutions",
    website: "techsolutions@example.com",
    address: "202 N Michigan Ave Chicago IL",
    postal_code: "60602",
  },
];

export interface Product {
  id: number;
  category: string;
  name: string;
  price: number;
  image: string;
}

export const productsData: Product[] = [
  {
    id: 1,
    category: "Mechanical Tools",
    name: "Carbon Steel Red Hand Plier",
    price: 280.99,
    image: Tool1,
  },
  {
    id: 2,
    category: "Electrical Tools",
    name: "Wire Cutter Pro",
    price: 150.5,
    image: Tool2,
  },
  {
    id: 3,
    category: "Mechanical Tools",
    name: "Adjustable Wrench",
    price: 75.25,
    image: Tool1,
  },
  {
    id: 4,
    category: "Electrical Tools",
    name: "Multimeter Digital",
    price: 120.0,
    image: Tool2,
  },
  {
    id: 5,
    category: "Mechanical Tools",
    name: "Screwdriver Set",
    price: 45.99,
    image: Tool1,
  },
  {
    id: 6,
    category: "Electrical Tools",
    name: "Voltage Tester",
    price: 35.75,
    image: Tool2,
  },
  {
    id: 7,
    category: "Mechanical Tools",
    name: "Pipe Wrench",
    price: 65.5,
    image: Tool1,
  },
  {
    id: 8,
    category: "Electrical Tools",
    name: "Circuit Breaker Finder",
    price: 89.99,
    image: Tool2,
  },
  {
    id: 9,
    category: "Mechanical Tools",
    name: "Pliers Set",
    price: 55.25,
    image: Tool1,
  },
  {
    id: 10,
    category: "Electrical Tools",
    name: "Cable Stripper",
    price: 32.99,
    image: Tool2,
  },
  {
    id: 11,
    category: "Mechanical Tools",
    name: "Socket Set",
    price: 110.0,
    image: Tool1,
  },
  {
    id: 12,
    category: "Electrical Tools",
    name: "Wire Crimper",
    price: 42.5,
    image: Tool2,
  },
  {
    id: 13,
    category: "Mechanical Tools",
    name: "Hammer",
    price: 25.99,
    image: Tool1,
  },
  {
    id: 14,
    category: "Electrical Tools",
    name: "Fish Tape",
    price: 18.75,
    image: Tool2,
  },
  {
    id: 15,
    category: "Mechanical Tools",
    name: "Tape Measure",
    price: 15.5,
    image: Tool1,
  },
  {
    id: 16,
    category: "Electrical Tools",
    name: "Conduit Bender",
    price: 95.0,
    image: Tool2,
  },
];

export const dummyVariants = [
  {
    id: 1,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-8IN",
    size: "8-Inch",
    color: "Red",
    price: "280.99",
    stock: 24,
    warranty: 3,
    material: "Mattel",
    manufacture_code: "15816500",
  },
  {
    id: 2,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-9IN",
    size: "9-Inch",
    color: "Blue",
    price: "300.49",
    stock: 12,
    warranty: 0,
    material: "",
    manufacture_code: "",
  },
  {
    id: 3,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-10IN",
    size: "10-Inch",
    color: "Green",
    price: "320.99",
    stock: 15,
    warranty: 3,
    material: "Metal",
    manufacture_code: "15816502",
  },
  {
    id: 4,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-11IN",
    size: "11-Inch",
    color: "Yellow",
    price: "310.00",
    stock: 10,
    warranty: 1,
    material: "Steel",
    manufacture_code: "15816503",
  },
  {
    id: 5,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-12IN",
    size: "12-Inch",
    color: "Black",
    price: "290.75",
    stock: 20,
    warranty: 4,
    material: "Aluminum",
    manufacture_code: "15816504",
  },
  {
    id: 6,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-13IN",
    size: "13-Inch",
    color: "Red",
    price: "305.00",
    stock: 25,
    warranty: 3,
    material: "Plastic",
    manufacture_code: "15816505",
  },
  {
    id: 7,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-14IN",
    size: "14-Inch",
    color: "White",
    price: "295.99",
    stock: 18,
    warranty: 2,
    material: "Wood",
    manufacture_code: "15816506",
  },
  {
    id: 8,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-15IN",
    size: "15-Inch",
    color: "Purple",
    price: "330.50",
    stock: 13,
    warranty: 5,
    material: "Carbon Fiber",
    manufacture_code: "15816507",
  },
  {
    id: 9,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-16IN",
    size: "16-Inch",
    color: "Grey",
    price: "310.25",
    stock: 9,
    warranty: 1,
    material: "Resin",
    manufacture_code: "15816508",
  },
  {
    id: 10,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-17IN",
    size: "17-Inch",
    color: "Cyan",
    price: "285.99",
    stock: 11,
    warranty: 2,
    material: "Composite",
    manufacture_code: "15816509",
  },
  {
    id: 11,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-18IN",
    size: "18-Inch",
    color: "Magenta",
    price: "340.00",
    stock: 22,
    warranty: 3,
    material: "Polymer",
    manufacture_code: "15816510",
  },
  {
    id: 12,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-19IN",
    size: "19-Inch",
    color: "Orange",
    price: "315.49",
    stock: 6,
    warranty: 4,
    material: "Steel",
    manufacture_code: "15816511",
  },
  {
    id: 13,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-20IN",
    size: "20-Inch",
    color: "Lime",
    price: "299.00",
    stock: 17,
    warranty: 3,
    material: "Plastic",
    manufacture_code: "15816512",
  },
  {
    id: 14,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-21IN",
    size: "21-Inch",
    color: "Teal",
    price: "325.00",
    stock: 8,
    warranty: 5,
    material: "Metal",
    manufacture_code: "15816513",
  },
  {
    id: 15,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-22IN",
    size: "22-Inch",
    color: "Pink",
    price: "298.95",
    stock: 30,
    warranty: 2,
    material: "Mattel",
    manufacture_code: "15816514",
  },
  {
    id: 16,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-23IN",
    size: "23-Inch",
    color: "Navy",
    price: "345.00",
    stock: 14,
    warranty: 3,
    material: "Fiber",
    manufacture_code: "15816515",
  },
  {
    id: 17,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-24IN",
    size: "24-Inch",
    color: "Brown",
    price: "335.75",
    stock: 19,
    warranty: 2,
    material: "Alloy",
    manufacture_code: "15816516",
  },
  {
    id: 18,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-25IN",
    size: "25-Inch",
    color: "Olive",
    price: "312.49",
    stock: 16,
    warranty: 1,
    material: "Resin",
    manufacture_code: "15816517",
  },
  {
    id: 19,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-26IN",
    size: "26-Inch",
    color: "Maroon",
    price: "328.00",
    stock: 7,
    warranty: 4,
    material: "Steel",
    manufacture_code: "15816518",
  },
  {
    id: 20,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-27IN",
    size: "27-Inch",
    color: "Tan",
    price: "355.99",
    stock: 5,
    warranty: 3,
    material: "Plastic",
    manufacture_code: "15816519",
  },
  {
    id: 21,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-8IN",
    size: "8-Inch",
    color: "Red",
    price: "280.99",
    stock: 24,
    warranty: 3,
    material: "Mattel",
    manufacture_code: "15816500",
  },
  {
    id: 22,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-9IN",
    size: "9-Inch",
    color: "Blue",
    price: "300.49",
    stock: 12,
    warranty: 0,
    material: "",
    manufacture_code: "",
  },
  {
    id: 23,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-10IN",
    size: "10-Inch",
    color: "Green",
    price: "320.99",
    stock: 15,
    warranty: 3,
    material: "Metal",
    manufacture_code: "15816502",
  },
  {
    id: 24,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-11IN",
    size: "11-Inch",
    color: "Yellow",
    price: "310.00",
    stock: 10,
    warranty: 1,
    material: "Steel",
    manufacture_code: "15816503",
  },
  {
    id: 25,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-12IN",
    size: "12-Inch",
    color: "Black",
    price: "290.75",
    stock: 20,
    warranty: 4,
    material: "Aluminum",
    manufacture_code: "15816504",
  },
  {
    id: 26,
    image_url: "https://ui.shadcn.com/avatars/05.png",
    sku: "CS-RHP-13IN",
    size: "13-Inch",
    color: "Red",
    price: "305.00",
    stock: 25,
    warranty: 3,
    material: "Plastic",
    manufacture_code: "15816505",
  },
  {
    id: 27,
    image_url: "https://ui.shadcn.com/avatars/01.png",
    sku: "CS-RHP-14IN",
    size: "14-Inch",
    color: "White",
    price: "295.99",
    stock: 18,
    warranty: 2,
    material: "Wood",
    manufacture_code: "15816506",
  },
  {
    id: 28,
    image_url: "https://ui.shadcn.com/avatars/02.png",
    sku: "CS-RHP-15IN",
    size: "15-Inch",
    color: "Purple",
    price: "330.50",
    stock: 13,
    warranty: 5,
    material: "Carbon Fiber",
    manufacture_code: "15816507",
  },
  {
    id: 29,
    image_url: "https://ui.shadcn.com/avatars/03.png",
    sku: "CS-RHP-16IN",
    size: "16-Inch",
    color: "Grey",
    price: "310.25",
    stock: 9,
    warranty: 1,
    material: "Resin",
    manufacture_code: "15816508",
  },
  {
    id: 30,
    image_url: "https://ui.shadcn.com/avatars/04.png",
    sku: "CS-RHP-17IN",
    size: "17-Inch",
    color: "Cyan",
    price: "285.99",
    stock: 11,
    warranty: 2,
    material: "Composite",
    manufacture_code: "15816509",
  },
];
